# Build. Node is deliberately not here: static/qompnt.css is generated by
# `make css` and committed, so the image never needs a JavaScript toolchain to
# produce CSS. Run `make css` before deploying if you changed any markup.
FROM golang:1.26-alpine AS build
WORKDIR /src

# No third-party modules, so there is nothing to download - go.mod is copied on
# its own anyway, to keep this layer cached when only sources change.
COPY go.mod ./
COPY . .

# CGO off makes the binary static, which is what lets the final stage be
# scratch. -s -w drop the symbol table and DWARF: the assets are embedded in
# here too, so trimming what is not needed at runtime is worth a few MB.
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /qompnt .

# scratch, not alpine: everything the server reads is embedded in the binary
# (see assets.go), so the image needs no filesystem, no shell and no package
# manager - which is also the smallest attack surface available.
FROM scratch

# The registry endpoint and the agent prompt serve absolute URLs, and anything
# fetching them over HTTPS needs a trust store. scratch has none.
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=build /qompnt /qompnt

# Documentation only - Cloud Run assigns the real port through $PORT, which
# main.go reads, and ignores whatever is declared here.
EXPOSE 8080

ENTRYPOINT ["/qompnt"]
