.PHONY: all css build qomp test dev kill clean

PORT ?= 8080

all: css build

# Scans markup for utility classes and writes the stylesheet. Committed output -
# consumers get a plain CSS file and never need Node.
# static/components.css is the other half: generated by the server from each
# component's styles.css on load, so it is always in step with what the site
# serves and with what the CSS tab shows.
css:
	npx unocss "components/**/*.html" "templates/**/*.html" -o static/qompnt.css

build: css
	go build -o qompnt .

# Thin installer CLI — pulls themes/components from the live registry.
qomp:
	go build -o qomp ./cmd/qomp

test:
	go test ./...

# kill first: an old process holding the port means `go run` dies on bind and you
# keep looking at the stale server, which reads as "the new code did nothing".
dev: css kill
	go run . -dev -addr :$(PORT)

kill:
	-@pkill -f "qompnt -addr" 2>/dev/null || true
	-@pkill -f "exe/qompnt" 2>/dev/null || true
	-@fuser -k $(PORT)/tcp 2>/dev/null || true
	@sleep 0.3

clean:
	rm -f qompnt qomp static/qompnt.css static/components.css
