.PHONY: all css build test dev kill clean deploy

PORT ?= 8080
SERVICE ?= qompnt
REGION ?= asia-south1

all: css build

# Scans markup for utility classes and writes the stylesheet. Committed output -
# consumers get a plain CSS file and never need Node.
# static/components.css is the other half: generated by the server from each
# component's styles.css on load, so it is always in step with what the site
# serves and with what the CSS tab shows.
css:
	npx unocss "components/**/*.html" "templates/**/*.html" -o static/qompnt.css

build: css
	go build -o qompnt .

test:
	go test ./...

# kill first: an old process holding the port means `go run` dies on bind and you
# keep looking at the stale server, which reads as "the new code did nothing".
dev: css kill
	go run . -dev -addr :$(PORT)

kill:
	-@pkill -f "qompnt -addr" 2>/dev/null || true
	-@pkill -f "exe/qompnt" 2>/dev/null || true
	-@fuser -k $(PORT)/tcp 2>/dev/null || true
	@sleep 0.3

# Deploy to Cloud Run. --source builds the Dockerfile on Cloud Build, so no
# local Docker daemon is involved. css first, and it matters: the stylesheet is
# generated from the markup and then embedded into the binary as it stands on
# disk, so a stale one ships silently.
deploy: css
	gcloud run deploy $(SERVICE) --source . --region $(REGION) --allow-unauthenticated

clean:
	rm -f qompnt static/qompnt.css static/components.css
