package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func writeFile(path string, body []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, body, 0o644)
}

// installStyles copies tokens, utilities, optional DS theme, and accent into
// cfg.Paths.Styles under project root.
func installStyles(root string, cfg Config, client *Client) error {
	m := client.Manifest
	if m == nil {
		return fmt.Errorf("manifest not loaded")
	}
	stylesDir := filepath.Join(root, filepath.FromSlash(cfg.Paths.Styles))

	tokens, err := fetchCached(client.HTTP, m.Assets.Tokens, "")
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(stylesDir, "tokens.css"), tokens); err != nil {
		return err
	}

	utils, err := fetchCached(client.HTTP, m.Assets.Utils, "")
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(stylesDir, "qompnt.css"), utils); err != nil {
		return err
	}

	themePath := filepath.Join(stylesDir, "theme.css")
	if cfg.Theme == "" || cfg.Theme == "claude" {
		_ = os.Remove(themePath)
	} else {
		t, ok := client.findTheme(cfg.Theme)
		if !ok {
			return fmt.Errorf("theme %q not in registry", cfg.Theme)
		}
		if t.URL == "" {
			return fmt.Errorf("theme %q has no stylesheet", cfg.Theme)
		}
		body, err := fetchCached(client.HTTP, t.URL, t.Hash)
		if err != nil {
			return err
		}
		if err := writeFile(themePath, body); err != nil {
			return err
		}
	}

	accentPath := filepath.Join(stylesDir, "accent.css")
	if cfg.Accent == "" {
		_ = os.Remove(accentPath)
	} else {
		if err := writeFile(accentPath, []byte(accentCSS(cfg.Accent))); err != nil {
			return err
		}
	}
	return nil
}

func accentCSS(hex string) string {
	hex = strings.TrimSpace(hex)
	fg := "#ffffff"
	if contrastBlack(hex) {
		fg = "#000000"
	}
	return fmt.Sprintf(`/* Generated by qomp — accent override */
:root, [data-theme="dark"] {
  --primary: %s;
  --primary-foreground: %s;
  --ring: %s;
}
`, hex, fg, hex)
}

// contrastBlack reports whether black text is more readable on hex than white.
func contrastBlack(hex string) bool {
	hex = strings.TrimPrefix(hex, "#")
	if len(hex) == 3 {
		hex = string([]byte{hex[0], hex[0], hex[1], hex[1], hex[2], hex[2]})
	}
	if len(hex) != 6 {
		return false
	}
	var r, g, b int
	_, err := fmt.Sscanf(hex, "%02x%02x%02x", &r, &g, &b)
	if err != nil {
		return false
	}
	// Relative luminance threshold (sRGB approx).
	l := (0.299*float64(r) + 0.587*float64(g) + 0.114*float64(b)) / 255
	return l > 0.55
}

// installComponent writes HTML into paths.components and CSS into paths.styles.
func installComponent(root string, cfg Config, client *Client, slug string) error {
	comp, ok := client.findComponent(slug)
	if !ok {
		return fmt.Errorf("no component named %q available", slug)
	}
	item, err := client.fetchItem(comp.URL)
	if err != nil {
		return err
	}
	compDir := filepath.Join(root, filepath.FromSlash(cfg.Paths.Components))
	stylesDir := filepath.Join(root, filepath.FromSlash(cfg.Paths.Styles))

	for _, f := range item.Files {
		name := filepath.Base(f.Target)
		if name == "." || name == "/" || name == "" {
			name = filepath.Base(f.Path)
		}
		var dest string
		switch {
		case strings.HasSuffix(name, ".css"):
			dest = filepath.Join(stylesDir, name)
		default:
			dest = filepath.Join(compDir, name)
		}
		if err := writeFile(dest, []byte(f.Content)); err != nil {
			return err
		}
	}
	return nil
}

func ensureComponentListed(cfg *Config, slug string) {
	for _, s := range cfg.Components {
		if s == slug {
			return
		}
	}
	cfg.Components = append(cfg.Components, slug)
}
